[2025-02-11T18:10:12.658+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-02-11T18:10:12.902+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: read_sqlite.read_sqlite_data manual__2025-02-11T18:10:06.447199+00:00 [queued]>
[2025-02-11T18:10:12.997+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: read_sqlite.read_sqlite_data manual__2025-02-11T18:10:06.447199+00:00 [queued]>
[2025-02-11T18:10:12.999+0000] {taskinstance.py:2867} INFO - Starting attempt 1 of 1
[2025-02-11T18:10:13.164+0000] {taskinstance.py:2890} INFO - Executing <Task(PythonOperator): read_sqlite_data> on 2025-02-11 18:10:06.447199+00:00
[2025-02-11T18:10:13.320+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=119) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-02-11T18:10:13.331+0000] {standard_task_runner.py:72} INFO - Started process 120 to run task
[2025-02-11T18:10:13.335+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'read_sqlite', 'read_sqlite_data', 'manual__2025-02-11T18:10:06.447199+00:00', '--job-id', '31', '--raw', '--subdir', 'DAGS_FOLDER/read_sqlite.py', '--cfg-path', '/tmp/tmp0jclqplr']
[2025-02-11T18:10:13.358+0000] {standard_task_runner.py:105} INFO - Job 31: Subtask read_sqlite_data
[2025-02-11T18:10:13.451+0000] {task_command.py:467} INFO - Running <TaskInstance: read_sqlite.read_sqlite_data manual__2025-02-11T18:10:06.447199+00:00 [running]> on host 1310df7a0a0e
[2025-02-11T18:10:13.816+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='read_sqlite' AIRFLOW_CTX_TASK_ID='read_sqlite_data' AIRFLOW_CTX_EXECUTION_DATE='2025-02-11T18:10:06.447199+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-02-11T18:10:06.447199+00:00'
[2025-02-11T18:10:13.821+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-02-11T18:10:13.947+0000] {read_sqlite.py:14} INFO - Connecting to SQLite database at /opt/***/data/nba.sqlite
[2025-02-11T18:10:13.979+0000] {read_sqlite.py:20} INFO - Tables found in SQLite database: []
[2025-02-11T18:10:13.981+0000] {python.py:240} INFO - Done. Returned value was: None
[2025-02-11T18:10:14.007+0000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-02-11T18:10:14.007+0000] {taskinstance.py:353} INFO - Marking task as SUCCESS. dag_id=read_sqlite, task_id=read_sqlite_data, run_id=manual__2025-02-11T18:10:06.447199+00:00, execution_date=20250211T181006, start_date=20250211T181012, end_date=20250211T181014
[2025-02-11T18:10:14.119+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-02-11T18:10:14.224+0000] {taskinstance.py:3901} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-02-11T18:10:14.227+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
