[2025-02-11T17:48:49.979+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-02-11T17:48:50.065+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: kaggle_to_s3_pipeline.upload_to_s3 manual__2025-02-11T17:48:40.476062+00:00 [queued]>
[2025-02-11T17:48:50.094+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: kaggle_to_s3_pipeline.upload_to_s3 manual__2025-02-11T17:48:40.476062+00:00 [queued]>
[2025-02-11T17:48:50.097+0000] {taskinstance.py:2867} INFO - Starting attempt 1 of 2
[2025-02-11T17:48:50.139+0000] {taskinstance.py:2890} INFO - Executing <Task(PythonOperator): upload_to_s3> on 2025-02-11 17:48:40.476062+00:00
[2025-02-11T17:48:50.198+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=121) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-02-11T17:48:50.205+0000] {standard_task_runner.py:72} INFO - Started process 123 to run task
[2025-02-11T17:48:50.209+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'kaggle_to_s3_pipeline', 'upload_to_s3', 'manual__2025-02-11T17:48:40.476062+00:00', '--job-id', '12', '--raw', '--subdir', 'DAGS_FOLDER/s3_data.py', '--cfg-path', '/tmp/tmpdsmodkhc']
[2025-02-11T17:48:50.213+0000] {standard_task_runner.py:105} INFO - Job 12: Subtask upload_to_s3
[2025-02-11T17:48:50.338+0000] {task_command.py:467} INFO - Running <TaskInstance: kaggle_to_s3_pipeline.upload_to_s3 manual__2025-02-11T17:48:40.476062+00:00 [running]> on host c9167234c945
[2025-02-11T17:48:50.465+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='kaggle_to_s3_pipeline' AIRFLOW_CTX_TASK_ID='upload_to_s3' AIRFLOW_CTX_EXECUTION_DATE='2025-02-11T17:48:40.476062+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-02-11T17:48:40.476062+00:00'
[2025-02-11T17:48:50.468+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-02-11T17:48:50.498+0000] {s3_data.py:28} INFO - Uploading nba.sqlite to S3 bucket None at nba_data/nba.sqlite
[2025-02-11T17:48:52.333+0000] {s3_data.py:39} ERROR - Error uploading to S3: expected string or bytes-like object, got 'NoneType'
[2025-02-11T17:48:52.336+0000] {python.py:240} INFO - Done. Returned value was: None
[2025-02-11T17:48:52.359+0000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-02-11T17:48:52.361+0000] {taskinstance.py:353} INFO - Marking task as SUCCESS. dag_id=kaggle_to_s3_pipeline, task_id=upload_to_s3, run_id=manual__2025-02-11T17:48:40.476062+00:00, execution_date=20250211T174840, start_date=20250211T174850, end_date=20250211T174852
[2025-02-11T17:48:52.458+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-02-11T17:48:52.508+0000] {taskinstance.py:3901} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-02-11T17:48:52.510+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
