[2025-02-11T16:25:34.395+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-02-11T16:25:34.416+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: read_sqlite.read_sqlite_data scheduled__2025-02-10T00:00:00+00:00 [queued]>
[2025-02-11T16:25:34.426+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: read_sqlite.read_sqlite_data scheduled__2025-02-10T00:00:00+00:00 [queued]>
[2025-02-11T16:25:34.430+0000] {taskinstance.py:2867} INFO - Starting attempt 1 of 1
[2025-02-11T16:25:34.446+0000] {taskinstance.py:2890} INFO - Executing <Task(PythonOperator): read_sqlite_data> on 2025-02-10 00:00:00+00:00
[2025-02-11T16:25:34.466+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=126) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-02-11T16:25:34.475+0000] {standard_task_runner.py:72} INFO - Started process 128 to run task
[2025-02-11T16:25:34.475+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'read_sqlite', 'read_sqlite_data', 'scheduled__2025-02-10T00:00:00+00:00', '--job-id', '3', '--raw', '--subdir', 'DAGS_FOLDER/read_sqlite.py', '--cfg-path', '/tmp/tmpppim9cnw']
[2025-02-11T16:25:34.483+0000] {standard_task_runner.py:105} INFO - Job 3: Subtask read_sqlite_data
[2025-02-11T16:25:34.590+0000] {task_command.py:467} INFO - Running <TaskInstance: read_sqlite.read_sqlite_data scheduled__2025-02-10T00:00:00+00:00 [running]> on host a4e66f9d6d3a
[2025-02-11T16:25:34.676+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='read_sqlite' AIRFLOW_CTX_TASK_ID='read_sqlite_data' AIRFLOW_CTX_EXECUTION_DATE='2025-02-10T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-02-10T00:00:00+00:00'
[2025-02-11T16:25:34.679+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-02-11T16:25:34.736+0000] {python.py:240} INFO - Done. Returned value was: None
[2025-02-11T16:25:34.748+0000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-02-11T16:25:34.749+0000] {taskinstance.py:353} INFO - Marking task as SUCCESS. dag_id=read_sqlite, task_id=read_sqlite_data, run_id=scheduled__2025-02-10T00:00:00+00:00, execution_date=20250210T000000, start_date=20250211T162534, end_date=20250211T162534
[2025-02-11T16:25:34.801+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-02-11T16:25:34.828+0000] {taskinstance.py:3901} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-02-11T16:25:34.829+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
[2025-02-11T17:49:10.075+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-02-11T17:49:10.110+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: read_sqlite.read_sqlite_data scheduled__2025-02-10T00:00:00+00:00 [queued]>
[2025-02-11T17:49:10.124+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: read_sqlite.read_sqlite_data scheduled__2025-02-10T00:00:00+00:00 [queued]>
[2025-02-11T17:49:10.125+0000] {taskinstance.py:2867} INFO - Starting attempt 1 of 1
[2025-02-11T17:49:10.136+0000] {taskinstance.py:2890} INFO - Executing <Task(PythonOperator): read_sqlite_data> on 2025-02-10 00:00:00+00:00
[2025-02-11T17:49:10.146+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=134) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-02-11T17:49:10.149+0000] {standard_task_runner.py:72} INFO - Started process 136 to run task
[2025-02-11T17:49:10.150+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'read_sqlite', 'read_sqlite_data', 'scheduled__2025-02-10T00:00:00+00:00', '--job-id', '14', '--raw', '--subdir', 'DAGS_FOLDER/read_sqlite.py', '--cfg-path', '/tmp/tmpa9o6jgeo']
[2025-02-11T17:49:10.153+0000] {standard_task_runner.py:105} INFO - Job 14: Subtask read_sqlite_data
[2025-02-11T17:49:10.208+0000] {task_command.py:467} INFO - Running <TaskInstance: read_sqlite.read_sqlite_data scheduled__2025-02-10T00:00:00+00:00 [running]> on host c9167234c945
[2025-02-11T17:49:10.344+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='read_sqlite' AIRFLOW_CTX_TASK_ID='read_sqlite_data' AIRFLOW_CTX_EXECUTION_DATE='2025-02-10T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-02-10T00:00:00+00:00'
[2025-02-11T17:49:10.345+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-02-11T17:49:10.362+0000] {read_sqlite.py:14} INFO - Connecting to SQLite database at /opt/***/data/nba.sqlite
[2025-02-11T17:49:10.365+0000] {read_sqlite.py:20} INFO - Tables found in SQLite database: []
[2025-02-11T17:49:10.366+0000] {python.py:240} INFO - Done. Returned value was: None
[2025-02-11T17:49:10.375+0000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-02-11T17:49:10.375+0000] {taskinstance.py:353} INFO - Marking task as SUCCESS. dag_id=read_sqlite, task_id=read_sqlite_data, run_id=scheduled__2025-02-10T00:00:00+00:00, execution_date=20250210T000000, start_date=20250211T174910, end_date=20250211T174910
[2025-02-11T17:49:10.414+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-02-11T17:49:10.429+0000] {taskinstance.py:3901} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-02-11T17:49:10.430+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
