[2025-02-11T23:41:01.082+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-02-11T23:41:01.096+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: kaggle_to_s3_pipeline.download_kaggle_data manual__2025-02-11T23:40:55.751176+00:00 [queued]>
[2025-02-11T23:41:01.103+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: kaggle_to_s3_pipeline.download_kaggle_data manual__2025-02-11T23:40:55.751176+00:00 [queued]>
[2025-02-11T23:41:01.103+0000] {taskinstance.py:2867} INFO - Starting attempt 1 of 2
[2025-02-11T23:41:01.112+0000] {taskinstance.py:2890} INFO - Executing <Task(PythonOperator): download_kaggle_data> on 2025-02-11 23:40:55.751176+00:00
[2025-02-11T23:41:01.131+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=139) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-02-11T23:41:01.133+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'kaggle_to_s3_pipeline', 'download_kaggle_data', 'manual__2025-02-11T23:40:55.751176+00:00', '--job-id', '77', '--raw', '--subdir', 'DAGS_FOLDER/s3_data.py', '--cfg-path', '/tmp/tmpblojeh05']
[2025-02-11T23:41:01.135+0000] {standard_task_runner.py:72} INFO - Started process 140 to run task
[2025-02-11T23:41:01.135+0000] {standard_task_runner.py:105} INFO - Job 77: Subtask download_kaggle_data
[2025-02-11T23:41:01.217+0000] {task_command.py:467} INFO - Running <TaskInstance: kaggle_to_s3_pipeline.download_kaggle_data manual__2025-02-11T23:40:55.751176+00:00 [running]> on host f9b3381e7066
[2025-02-11T23:41:01.283+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='kaggle_to_s3_pipeline' AIRFLOW_CTX_TASK_ID='download_kaggle_data' AIRFLOW_CTX_EXECUTION_DATE='2025-02-11T23:40:55.751176+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-02-11T23:40:55.751176+00:00'
[2025-02-11T23:41:01.285+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-02-11T23:41:01.407+0000] {s3_data.py:30} INFO - Downloading dataset wyattowalsh/basketball to /opt/***/data
[2025-02-11T23:41:01.419+0000] {s3_data.py:38} ERROR - Download failed! /opt/***/data/nba.sqlite not found.
[2025-02-11T23:41:01.420+0000] {python.py:240} INFO - Done. Returned value was: None
[2025-02-11T23:41:01.438+0000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-02-11T23:41:01.439+0000] {taskinstance.py:353} INFO - Marking task as SUCCESS. dag_id=kaggle_to_s3_pipeline, task_id=download_kaggle_data, run_id=manual__2025-02-11T23:40:55.751176+00:00, execution_date=20250211T234055, start_date=20250211T234101, end_date=20250211T234101
[2025-02-11T23:41:01.490+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-02-11T23:41:01.514+0000] {taskinstance.py:3901} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-02-11T23:41:01.515+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
